### ISSUE TITLE
Provide guidance on Rebuild and Upstream timers

### ISSUE THREAD

**Issue by embano1** [openfaas/connector-sdk#45]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

For controller authors it would be nice to provide some guidance on sensible defaults for `RebuildInterval` and `UpstreamTimeout`. Currently, if none if these are provided it's unclear what the defaults are (in the case of `UpstreamTimeout` there is no timeout at all which could cause blocking issues during network/API problems).

## Expected Behaviour

Provide guidance (docs) on sensible defaults or check provided values (empty) in the code and enforce timeouts respectively.

## Current Behaviour

If neither of these intervals/timeouts are specified the behavior of the connector using the SDK is undetermined, especially in cases of network/API interruptions.

## Possible Solution

- Update docs
- Enforce timeouts in code

**Comment by alexellis** [comment]
Sounds good to me, can you suggest where to do this? The README / tester app are the two places I can think of.

**Comment by embano1** [comment]
Yep, those two please :)
