### ISSUE TITLE
[Feature Request] Allow to set custom header fields

### ISSUE THREAD

**Issue by JonasDoe** [openfaas/connector-sdk#52]
At the moment there's no possibility to add HTTP header fields to the `invoke` function.
I've found this [issue](https://github.com/openfaas/connector-sdk/issues/37) addressing the same feature, but it was solved in a way I don't understand (afaik the `http` package does not allow you to set header fields via the `Context`) and probably solved only his own issue (the tracing). Additionally, there was already a [PR](https://github.com/openfaas/connector-sdk/pull/30) with a possible solution, but it died halfway.

Our case: We're working with CloudEvents and need to set the `Content-Type` to `application/cloudevents+json` to make relating sdk (https://github.com/cloudevents/sdk-go) at the function work properly.

I think the custom header fields could be set in the `ControllerConfig`, but maybe that's to general, or passed as an argument for `Invoke` and `InvokeWithContext` methods. Another option to keep the method's signature lean would be to support custom header fields in the `Context` passed by `InvokeWithContext` (a bit diverting though), or establish some kind of `InvocationOptions` type as an argument which holds custom headers and maybe other settings in future.

**Comment by JonasDoe** [comment]
I'ld be willing to provide a new PR, but in that case I'ld need a preference about how to implement that. In `ControllerConfig`? As an argument? In the `Context`? With `InvocationOptions`? In a completely different way?

**Comment by rshlapak-altair** [comment]
This feature can solve another issue:
  Payload is not passed from connector to function.
Event tester example doesn't work properly - body is always empty in called function.

I made it working by adding next line in invoker.go:90 (func invokefunction)
httpReq.Header.Set("Content-Type", "text/plain")

Any advices?

**Comment by mathieuforest** [comment]
@rshlapak-altair same issue here.

**Comment by alexellis** [comment]
> Payload is not passed from connector to function. Event tester example doesn't work properly - body is always empty in called function.

Please raise your own issue and detail everything you're using. Including the template.
