### ISSUE TITLE
Allow user to pass context to the controller

### ISSUE THREAD

**Issue by embano1** [openfaas/connector-sdk#7]
Currently the controller does not offer a way for coordinated/graceful shutdown. There's also a risk of go routine leaks, e.g. here: https://github.com/openfaas-incubator/connector-sdk/blob/bb7e84c27a54ab641317d26961300ed92aea739e/types/controller.go#L61

Proposal: accept a context and propagate/react to `ctx.Done()`:

```go
func NewController(ctx context.Context, credentials *auth.BasicAuthCredentials, config *ControllerConfig) *Controller {

	invoker := Invoker{
		PrintResponse: config.PrintResponse,
		Client:        MakeClient(config.UpstreamTimeout),
		GatewayURL:    config.GatewayURL,
	}
	topicMap := NewTopicMap()

	return &Controller{
		Config:      config,
		Invoker:     &invoker,
		TopicMap:    &topicMap,
		Credentials: credentials,
	}
}
```

Please comment on whether this would be an improvement, and how we should make use of `context`, e.g. embedding it into the `controller struct`, change downstream function signatures to enforce the context, use a `<-stopCh` or bool to signal shutdown, etc.

**Comment by Templum** [comment]
The question is does it really leak? It is intended to be consumed inside a controller, which basically sits there and just waits for incoming traffic, syncing in the background with the gateway. And as this probably running on a container, the lifecycle ends with the death of the container. 

I mean it is still a valid point.

**Comment by embano1** [comment]
As the SDK grows in functionality over time, there's a potential result of leaking go routines without explicitly stopping them.

My main point though was allowing a clean shutdown of the controller-sdk with a context to signal to downstream services, make use of the context in http downstream calls, etc.

**Comment by alexellis** [comment]
My thinking is similar to that of @Templum 

Alex

**Comment by embano1** [comment]
With the recent changes made by @alexellis running a Goroutine on `chan InvokerResponse` I still think it's useful to return all responses before the controller shuts down, e.g. SIGTERM. This is just a clean way of handling all responses before main() exits. Otherwise, the controller could miss responses, especially errs, which are important for logging/debugging.

[1]
https://github.com/openfaas-incubator/connector-sdk/blob/d722c9f72ad06903f416d1bc89878ba5a824b227/types/controller.go#L77

**Comment by alexellis** [comment]
In practice you cannot extend the Pod lifetime indefinitely, but we could stop forwarding messages when we get a SIG message coming in. You can see how this is handled in the watchdog code for a graceful shutdown.

**Comment by alexellis** [comment]
Thanks for cleaning up :+1:
